### ISSUE TITLE
DailyDuty报错

### ISSUE THREAD

**Issue by LittleNightmare** [ottercorp/DalamudPlugins#121]
![0D{XM77 P2FYSD`5M3ZW} C](https://user-images.githubusercontent.com/19811879/163703230-e6ff5dd9-17d0-4125-b3a6-4c6b6be9d83e.jpg)

@NiGuangOwO

问题在这里，国服就一直是0
https://github.com/NiGuangOwO/DailyDuty/blob/5a7ace921d946b9b4a92b396fd75e638f500b220/DailyDuty/Utilities/Helpers/JumboCactpot/DatacenterLookup.cs#L10

**Comment by NiGuangOwO** [comment]
#122 已修复
