### ISSUE TITLE
国服Lumina可以考虑修改一部分内容，增加国际服搬运插件的兼容性

### ISSUE THREAD

**Issue by LittleNightmare** [ottercorp/DalamudPlugins#149]
国服的数据一部分可能是因为国服没有DC特化或者省略过，想进行一些修改，这样可以减少一些插件在在这种情况下出现的误判

我提议参考@AsterOcclu在本地化插件中添加[Utils4CN](https://github.com/AsterOcclu/FFXIV_RpToolboxCN/blob/master/RoleplayersToolbox/Utils4CN/Init.cs)对Lumina的改动，修改国服lumina的数据，让部分涉及的插件直接可用，不用再单独的加服务器了

或者可以考虑做一个单独的项目，给Lumina找不同，往国际服数据靠拢？ ~~本质上是给拂晓擦屁股~~

**Comment by Bluefissure** [comment]
建议不要修改Lumina的数据，会影响到其他插件。

**Comment by LittleNightmare** [comment]
我认为只针对国服服务器问题修改Lumina的数据是可行的，并不会造成负面影响。目前在处理服务器我印象中有基本分为两个情况

1. 对于国服插件，一般的解决方案都是手写了一个服务器表
2. 国际服插件一般是从Lumina直接拿服务器列表的

对于情况1，修改lumina数据不影响插件运行。

在情况2中，修改了lumina数据可以直接让插件检索服务器表的部分正常运行。

另外，我觉得没有插件能从国服现在Lumina的服务器表，获取到有用的信息

我想尝试将[Utils4CN](https://github.com/AsterOcclu/FFXIV_RpToolboxCN/blob/master/RoleplayersToolbox/Utils4CN/Init.cs)的功能单独做一个插件出来，类似IMEPlugin
